### ISSUE TITLE
Fix client runtime error

### ISSUE THREAD

**Issue by saboonikhil** [zeitgeistpm/discord-faucet#4]
```
/root/discord-faucet/node_modules/discord.js/src/client/actions/MessageCreate.js:11
      const existing = channel.messages.cache.get(data.id);
                                        ^

TypeError: Cannot read property 'cache' of undefined
    at MessageCreateAction.handle (/root/discord-faucet/node_modules/discord.js/src/client/actions/MessageCreate.js:11:41)
    at Object.module.exports [as MESSAGE_CREATE] (/root/discord-faucet/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/root/discord-faucet/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/root/discord-faucet/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/root/discord-faucet/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/root/discord-faucet/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/root/discord-faucet/node_modules/ws/lib/websocket.js:983:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.dataMessage (/root/discord-faucet/node_modules/ws/lib/receiver.js:517:14)
  ```

**Comment by saboonikhil** [comment]
On restarting the app, the client seem to be running fine both on local and prod. Keeping a watch!
